---
kind: Namespace
apiVersion: v1
metadata:
  name: temp-atlassian
  labels:
    name: temp-atlassian
---
kind: Service
apiVersion: v1
metadata:
  name: confluence-service
  namespace: temp-atlassian
spec:
  selector:
    app: confluence
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8090
  type: NodePort
---
kind: Service
apiVersion: v1
metadata:
  name: postgres-service
  namespace: temp-atlassian
spec:
  selector:
    app: postgres
  ports:
  - name: psql
    port: 5432
    protocol: TCP
    targetPort: 5432
  clusterIP: None
---
kind: Service
apiVersion: v1
metadata:
  name: jira-service
  namespace: temp-atlassian
spec:
  selector:
    app: jira
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: confluence
  namespace: temp-atlassian
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: confluence
    spec:
      volumes:
      - name: app-data
        hostPath:
          path: /mergerFS/pool/temp-atlassian/confluence_data
      containers:
      - name: confluence
        image: atlassian/confluence-server
        volumeMounts:
        - name: app-data
          mountPath: /var/atlassian/application-data/confluence
        env:
        - name: ATL_PROXY_NAME
          value: 'temp.kbmanseau.com'
        - name: ATL_PROXY_PORT
          value: '443'
        - name: ATL_TOMCAT_SCHEME
          value: 'https'
        - name: ATL_TOMCAT_SECURE
          value: 'true'
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jira
  namespace: temp-atlassian
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jira
    spec:
      volumes:
      - name: app-data
        hostPath:
          path: /mergerFS/pool/temp-atlassian/jira_data
      containers:
      - name: jira
        image: cptactionhank/atlassian-jira
        volumeMounts:
        - name: app-data
          mountPath: /var/atlassian/jira
        env:
        - name: X_PROXY_NAME
          value: 'jira-temp.kbmanseau.com'
        - name: X_PROXY_PORT
          value: '443'
        - name: X_PROXY_SCHEME
          value: 'https'
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: temp-atlassian
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: data
        hostPath:
          path: /mergerFS/pool/temp-atlassian/postgres
      containers:
      - name: postgres
        image: postgres:9.6
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data/pgdata
        env:
        - name: POSTGRES_PASSWORD
          value: 'temp123'
        - name: PGDATA
          value: '/var/lib/postgresql/data/pgdata'
