apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-server-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/issuer: "letsencrypt-staging"
  namespace: plex
spec:
  tls:
  - hosts:
    - kbmanseau.com
    secretName: media-server
  rules:
  - host: sab.kbmanseau.com
    http:
      paths:
      - path: /
        backend:
          serviceName: sabnzbd-service
          servicePort: 8080
